services:
  - type: web
    name: gaurvideep-api
    runtime: docker
    dockerfilePath: ./service/Dockerfile
    dockerContext: .
    plan: starter
    region: oregon
    envVars:
      - key: PORT
        value: "10000"
      - key: CACHE_REFRESH_HOURS
        value: "24"
      - key: API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true